export const RULE_CREATED_CHANNEL_PREFIX = 'RULE_CREATED:';
export const RULE_DELETED_CHANNEL_PREFIX = 'RULE_DELETED:';
export const RULE_ALERT_DELETED_CHANNEL_PREFIX = 'RULE_ALERT_DELETED:';

export const QUEUE_REGISTERED_PREFIX = 'QUEUE_REGISTERED:';
export const QUEUE_UNREGISTERED_PREFIX = 'QUEUE_UNREGISTERED:';
export const QUEUE_DELETED_PREFIX = 'QUEUE_DELETED:';

export const NOTIFICATION_CHANNEL_ADDED_PREFIX = 'CHANNEL_ADDED:';
export const NOTIFICATION_CHANNEL_DELETED_PREFIX = 'CHANNEL_DELETED:';
