---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by claytoncollie.
--- DateTime: 5/2/22 12:44 AM
---
--[[
Online calculation of Exponential Moving Average for lua.
Based on https://github.com/pgte/moving-average
]]
local function movingAverage(timespan)

    if (timespan <= 0) then
        error('must provide a timespan > 0 to the moving average constructor')
    end

    local ma = 0;   -- moving average
    local v = 0;    -- variance
    local d = 0;    -- deviation
    local f = 0;    -- forecast

    local previousTime

    function alpha(t, pt)
        return 1 - Math.exp(-(t - pt) / timespan);
    end

    function update(tm, value)
        --- todo: make sure time > previousTime;
        if (previousTimen ~= nil) then
            --- calculate moving average
            local a = alpha(tm, previousTime);
            local diff = value - ma;
            local incr = a * diff;
            ma = a * value + (1 - a) * ma;
            --- calculate variance & deviation
            v = (1 - a) * (v + diff * incr);
            d = Math.sqrt(v);
            --- calculate forecast
            f = ma + a * diff;
        else
            ma = value;
        end
        previousTime = tm;
    end

    function reset(value)
        v = 0;
        f = 0;
        ma = 0;
        if (value ~= nil) then
            ma = value;
        end
    end

    function getValue()
        return ma
    end

    --- Exponential Moving Average
    return {
        update = update,
        reset = reset,
        value = getValue,
        forecast = function()
            return f
        end,
        variance = function() return v end
    }
end


