export enum JobSubscriptionType {
  JOB_ADDED = 'JOB_ADDED',
  JOB_DELETED = 'JOB_DELETED',
  JOB_UPDATED = 'JOB_UPDATED',
  JOB_COMPLETED = 'JOB_COMPLETED',
  JOB_FAILED = 'JOB_FAILED',
  JOB_FINISHED = 'JOB_FINISHED',
  JOB_LOG_ADDED = 'JOB_LOG_ADDED',
}
