---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ccollie.
--- DateTime: 10/22/20 2:06 AM
---

local function parseBool(val)
  if type(val) == 'number' then
    return val ~= 0
  end
  if (val == '1' or val == 't') then
    return true
  end
  return false
end

local function parseDots(str)
  local keys = {}
  for key in str:gmatch "[^.]+" do
    table.insert(keys, key)
  end
  return keys
end

local function get_ids_by_range(key, start, last, asc)
  local items = {}
  local count = last - start + 1
  local type = redis.call("TYPE", key)
  type = type["ok"]

  asc = parseBool(asc)
  if type == 'zset' then
    local command = asc and 'zrange' or 'zrevrange'
    items = redis.call(command, key, start, last)
  elseif type == "list" then
    if (asc) then
      local _start = -(last + 1)
      local _end = -(start + 1)
      items = redis.call("lrange", _start, _end)
    else
      items = redis.call("lrange", start, last)
    end
  elseif type == "set" then
    items = redis.call("SMEMBERS", key)
  end

  return items
end
