percentiles: [0.25, 0.5, 0.75, 0.9, 0.95, 0.99, 0.995]
snapshotInterval: 10000
aggregateInterval: 60000
flushInterval: 1000
lockTTL: 15000
stats_prefix: pamplona
hosts:
  - name: 'AWS Server 2'
    host: '127.0.0.1'
    port: 6379
    prefix: 'bull'
    queues:
      - name: 'bb_queue'
        prefix: 'bbq'
        jobTypes: []
      - name: suzy_queue
      - name: widgets
      - name: tacos
      - name: backup
